[package]
name = "dancing_crate"
version = "0.2.4"
authors = ["paramjit"]
license ="MIT/Apache-2.0"
readme="README.md"
repository="https://github.com/HobDev/dancing_crate.git"
description="""
TEST Project
"""



[dependencies]
