[package]
name = "Test_project"
version = "0.2.2"
authors = ["paramjit"]
license ="MIT/Apache-2.0"
readme="README.md"
repository="https://github.com/HobDev/iot_hub"
description="""
TEST Project
"""



[dependencies]
